image: php:7.2

before_script:
  - apt-get update && apt-get install -y git unzip
  - echo 'phar.readonly = off' > /usr/local/etc/php/conf.d/custom.ini
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  - composer install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - vendor/bin/phpunit tests
  only:
    - tags
  except:
    - branches

deploy:
  stage: deploy
  script:
    - vendor/bin/pake build
    - vendor/bin/pake upload
  only:
    - tags
  except:
    - branches
